name = "lean_codec"
version = "0.1.0"
defaultTargets = ["lean_codec", "run_tests"]

[[lean_lib]]
name = "LeanCodec"

[[lean_lib]]
name = "LeanCodecTest"

[[lean_exe]]
name = "lean_codec"
root = "Main"

[[lean_exe]]
name = "run_tests"
root = "LeanCodecTest.Main"
